dartApi:
  apiKey: "c3612ac797677127e1e6deacaf24a602599a9d5c"
  searchDisclosure:
    method: "get"
    url: "https://opendart.fss.or.kr/api/list.json"

crons:
  DART-DISCLOSURE: "*/10 * * * * *"

kakaoApi:
  apiKey: "kakaoKey"

slackApi:
  botToken: "xoxb-1077989743508-1084451024129-uf3BWd24H6XD1hDI8S9GJZUF"
  postMessage:
    method: "post"
    url: "https://slack.com/api/chat.postMessage"
    channel: "C0123Q5A5MG"

filterKeywords:
  - "단일판매"
  - "시장"


