dartApi:
  apiKey: "c3612ac797677127e1e6deacaf24a602599a9d5c"
  searchDisclosure:
    method: "get"
    url: "https://opendart.fss.or.kr/api/list.json"

crons:
  DART-DISCLOSURE: "*/10 * * * * *"

kakaoApi:
  apiKey: "kakaoKey"

slack:
  botToken: ""
  apis:
    - name: "postMessage"
      method: "post"
      url: "https://slack.com/api/chat.postMessage"

  channels:
    - name: "stock-alarm"
      id: "C0123Q5A5MG"


filterKeywords:
  - "단일판매"



